# Generated by Django 5.0 on 2023-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animal_image_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='serial_number',
            field=models.CharField(default=10, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
