# Generated by Django 5.0 on 2023-12-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='animals.type'),
            preserve_default=False,
        ),
    ]
