# Generated by Django 5.0 on 2023-12-13 14:20

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.NewUserManager()),
            ],
        ),
    ]
