# Generated by Django 5.0 on 2023-12-14 11:53

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=phone_field.models.PhoneField(default=10, max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
