# Generated by Django 5.0 on 2023-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=10, upload_to='avatar/'),
            preserve_default=False,
        ),
    ]
